/*UPDATE CLIENTE
SET CIDADE = 'Votorantim' 
WHERE NOME ='LOJAS AVENIDA LTDA';


UPDATE VENDEDOR
SET SALARIO = ((SALARIO *10)/100 + SALARIO)
WHERE NOME = 'MARCOS SILVA SALAZAR'
*/

/*
INSERT INTO VENDEDOR
VALUES ('ALCEU DISPOR', 10000)

SELECT * FROM VENDEDOR


DELETE PRODUTO
WHERE DESCRICAO = 'Cafeteira';

SELECT * FROM PRODUTO;


SELECT PEDIDO.NUMERO, CLIENTE.NOME, VENDEDOR.NOME, PRODUTO.DESCRICAO, PRODUTO.VALOR, PEDIDO.DATA
FROM PEDIDO
INNER JOIN VENDEDOR ON (PEDIDO.CODVEN = VENDEDOR.CODVEN)
INNER JOIN CLIENTE ON (PEDIDO.CODCLI = CLIENTE.CODCLI)
INNER JOIN PRODUTO ON (PEDIDO.CODPROD = PRODUTO.CODPROD);
*/

SELECT VENDEDOR.NOME, SUM(PRODUTO.VALOR)VALOR, SUM(PRODUTO.VALOR)*0.1 COMISSAO, SUM(PRODUTO.VALOR)*0.1 
FROM PEDIDO
INNER JOIN VENDEDOR ON (PEDIDO.CODVEN = VENDEDOR.CODVEN)
INNER JOIN CLIENTE ON (PEDIDO.CODCLI = CLIENTE.CODCLI)
INNER JOIN PRODUTO ON (PEDIDO.CODPROD = PRODUTO.CODPROD)
GROUP BY VENDEDOR.NOME


